ParkingLotInit = 'Created a parking lot with {0} slots'
Parked = 'Allocated slot number: {0}'
ParkingLotFull = 'Sorry, parking lot is full'
NotFound = 'Not Found'
SlotFreed = 'Slot number {0} is free'
TryAgain = 'Invalid Input, Try Again!'
InvalidAction = 'Invalid Action, Try Again!'
MustCreateParkingLot = 'You must create parking lot first!'
#Exceptions
SlotAlreadyFree = 'Slot {0} already free'
InvalidInput = 'Invalid Input'
ExitServiceCantInit = 'ExitService Cannot create Parking Lot'
SlotUnAvailable = 'Slot Not Available'
ReparkNotAllowed = 'Cannot park already Parked Car: {0}'
UnknownErrorOccured = 'Unkown Error Occured'